export const hotels = [
  {
    id: 1,
    name: "Hotel Arts Barcelona",
    rating: 5,
    reviews: 1200,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Olimpic",
    distance: "1.8 km from centre",
    beachDistance: "200 m from beach",
    type: "Luxury Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "40 m²",
    price: 1500,
    originalPrice: 1800,
    discount: "16% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access", "Breakfast included"],
    badge: "Gateway Deal",
    metroAccess: true,
  },
  {
    id: 2,
    name: "W Barcelona",
    rating: 5,
    reviews: 1300,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
    ],
    location: "Barceloneta",
    distance: "2.1 km from centre",
    beachDistance: "Direct beachfront",
    type: "Beach Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "35 m²",
    price: 1395,
    nights: 5,
    adults: 2,
    features: ["Breakfast included", "Spa access"],
    badge: "Best Location",
    metroAccess: true,
  },
  {
    id: 3,
    name: "Eurostars Grand Marina",
    rating: 4,
    reviews: 1100,
    score: 8.4,
    scoreLabel: "Very Good",
    images: [
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Vell",
    distance: "1.5 km from centre",
    beachDistance: "900 m from beach",
    type: "Harbourfront Hotel",
    roomType: "Deluxe Room",
    bedType: "King Bed",
    size: "33 m²",
    price: 1200,
    originalPrice: 1400,
    discount: "14% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access"],
    metroAccess: false,
  },
  {
    id: 4,
    name: "Hotel Arts Barcelona",
    rating: 5,
    reviews: 1200,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/majestic-hotel.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
    ],
    location: "Port Olimpic",
    distance: "1.8 km from centre",
    beachDistance: "200 m from beach",
    type: "Luxury Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "40 m²",
    price: 1500,
    originalPrice: 1800,
    discount: "16% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access", "Breakfast included"],
    badge: "Gateway Deal",
    metroAccess: true,
  },
  {
    id: 5,
    name: "W Barcelona",
    rating: 5,
    reviews: 1300,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Barceloneta",
    distance: "2.1 km from centre",
    beachDistance: "Direct beachfront",
    type: "Beach Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "35 m²",
    price: 1395,
    nights: 5,
    adults: 2,
    features: ["Breakfast included", "Spa access"],
    badge: "Best Location",
    metroAccess: true,
  },
  {
    id: 6,
    name: "Eurostars Grand Marina",
    rating: 4,
    reviews: 1100,
    score: 8.4,
    scoreLabel: "Very Good",
    images: [
      "assets/images/w-barcelona.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Vell",
    distance: "1.5 km from centre",
    beachDistance: "900 m from beach",
    type: "Harbourfront Hotel",
    roomType: "Deluxe Room",
    bedType: "King Bed",
    size: "33 m²",
    price: 1200,
    originalPrice: 1400,
    discount: "14% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access"],
    metroAccess: false,
  },
  {
    id: 7,
    name: "Hotel Arts Barcelona",
    rating: 5,
    reviews: 1200,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Olimpic",
    distance: "1.8 km from centre",
    beachDistance: "200 m from beach",
    type: "Luxury Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "40 m²",
    price: 1500,
    originalPrice: 1800,
    discount: "16% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access", "Breakfast included"],
    badge: "Gateway Deal",
    metroAccess: true,
  },
  {
    id: 8,
    name: "W Barcelona",
    rating: 5,
    reviews: 1300,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/majestic-hotel.jpg",
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
    ],
    location: "Barceloneta",
    distance: "2.1 km from centre",
    beachDistance: "Direct beachfront",
    type: "Beach Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "35 m²",
    price: 1395,
    nights: 5,
    adults: 2,
    features: ["Breakfast included", "Spa access"],
    badge: "Best Location",
    metroAccess: true,
  },
  {
    id: 9,
    name: "Eurostars Grand Marina",
    rating: 4,
    reviews: 1100,
    score: 8.4,
    scoreLabel: "Very Good",
    images: [
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Vell",
    distance: "1.5 km from centre",
    beachDistance: "900 m from beach",
    type: "Harbourfront Hotel",
    roomType: "Deluxe Room",
    bedType: "King Bed",
    size: "33 m²",
    price: 1200,
    originalPrice: 1400,
    discount: "14% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access"],
    metroAccess: false,
  },
  {
    id: 10,
    name: "Hotel Arts Barcelona",
    rating: 5,
    reviews: 1200,
    score: 9.0,
    scoreLabel: "Excellent",
    images: [
      "assets/images/hotel-arts-barcelona.jpg",
      "assets/images/w-barcelona.jpg",
      "assets/images/eurostars-grand-marina.jpg",
      "assets/images/majestic-hotel.jpg",
    ],
    location: "Port Olimpic",
    distance: "1.8 km from centre",
    beachDistance: "200 m from beach",
    type: "Luxury Hotel",
    roomType: "Sea View Room",
    bedType: "King Bed",
    size: "40 m²",
    price: 1500,
    originalPrice: 1800,
    discount: "16% off",
    nights: 5,
    adults: 2,
    features: ["Free cancellation", "Spa access", "Breakfast included"],
    badge: "Gateway Deal",
    metroAccess: true,
  },
];
